version: '3.5'
services:
    app:
        image: app:tag
        build: ./docker
        user: ${DEV_UID}:${DEV_GID}
        volumes:
            - ./:/var/www:cached
            - ${SSH_AUTH}:/tmp/.ssh-auth-sock
            - ${HOME}/dev/.composer:${HOME}/dev/.composer:cached
        environment:
            - APP_ENV=dev
            - KERNEL_CLASS=CommonsBundleTests\Kernel
            - DEV_UID=${DEV_UID}
            - DEV_GID=${DEV_GID}
            - COMPOSER_HOME=${HOME}/dev/.composer
            - MONGODB_DSN=mongodb://mongo
            - MONGODB_DB=commons
            - MARIADB_DSN=mariadb
            - MARIADB_DB=commons
            - MARIADB_USER=root
            - MARIADB_PASS=root
            - METRICS_SERVICE=influx
            - INFLUXDB_HOST=influxdb

    mongo:
        image: mongo:latest
        volumes:
            - mongo:/data/db

    mariadb:
        image: mariadb:latest
        command: "mysqld --innodb_flush_method=nosync"
        environment:
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - mariadb:/var/lib/mysql

    influxdb:
        image: influxdb:alpine
        volumes:
            - influxdb:/var/lib/influxdb
            - ./tests/testApp/influx/influxdb.conf:/etc/influxdb/influxdb.conf

volumes:
    mongo: {}
    mariadb: {}
    influxdb: {}
