version: '3'
services:
    app:
        image: dkr.hanaboso.net/pipes/pipes/php-dev:dev
        user: ${DEV_UID}:${DEV_GID}
        volumes:
            - ./:/var/www
            - ${SSH_AUTH_SOCK}:/tmp/bound-ssh-agent
            - ${HOME}/.composer:/srv/.composer
        environment:
            - APP_ENV=dev
            - KERNEL_CLASS=CommonsBundleTests\Kernel
            - DEV_UID=${DEV_UID}
            - DEV_GID=${DEV_GID}

    mongo:
        image: mongo:latest
        volumes:
            - mongo:/data/db

    mariadb:
        image: mariadb:latest
        command: "mysqld --innodb_flush_method=nosync"
        environment:
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - mariadb:/var/lib/mysql

    redis:
        image: redis:alpine
        volumes:
            - redis:/data

    influxdb:
        image: influxdb:alpine
        volumes:
            - influxdb:/var/lib/influxdb
            - ./tests/testApp/influx/influxdb.conf:/etc/influxdb/influxdb.conf

    fakes3:
        image: olalond3/fakes3

volumes:
    mongo: {}
    mariadb: {}
    redis: {}
    influxdb: {}
