services:
    _defaults:
        public: '%public.services%'

    hbpf.transport.curl_client_factory:
        class: Hanaboso\CommonsBundle\Transport\Curl\CurlClientFactory

    hbpf.transport.soap_client_factory:
        class: Hanaboso\CommonsBundle\Transport\Soap\SoapClientFactory
        arguments:
        calls:
            - ['setLogger', ['@monolog.logger.commons']]

    hbpf.redirect:
        class: Hanaboso\CommonsBundle\Redirect\Redirect