parameters:
    database_type: 'ODM' # 'ORM'

    env(AWS_KEY): key
    aws_key: '%env(string:AWS_KEY)%'

    env(AWS_SECRET): secret
    aws_secret: '%env(string:AWS_SECRET)%'

    env(AWS_BUCKET): bucket
    aws_bucket: '%env(string:AWS_BUCKET)%'

    metrics_service: '%env(string:METRICS_SERVICE)%'

    #MongoDb sender
    mongodb.monolith_table: monolith
    mongodb.connector_table: connectors
    mongodb.node_table: pipes_node
    mongodb.rabbit_table: rabbitmq
    mongodb.counter_table: pipes_counter
