parameters:
    database_type: 'ODM' # 'ORM'

    env(AWS_KEY): key
    aws_key: '%env(AWS_KEY)%'

    env(AWS_SECRET): secret
    aws_secret: '%env(AWS_SECRET)%'

    env(AWS_BUCKET): bucket
    aws_bucket: '%env(AWS_BUCKET)%'

    env(METRICS_SERVICE): influx
    metrics_service: '%env(METRICS_SERVICE)%'

    #MongoDb sender
    mongodb.monolith_table: monolith
    mongodb.connector_table: connectors
    mongodb.node_table: bridges
    mongodb.rabbit_table: rabbitmq
    mongodb.counter_table: pipes_counter
